# Generated by Django 5.0.1 on 2024-01-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userpassword_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField()),
                ('private', models.BooleanField(default=True)),
                ('provider_type', models.CharField(choices=[('1', 'Social'), ('2', 'Game'), ('3', 'Development')], default='1', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='game_developer',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='userpassword',
            name='website_url',
        ),
        migrations.AddField(
            model_name='userpassword',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpassword',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.provider'),
            preserve_default=False,
        ),
    ]
