# Generated by Django 4.1.5 on 2024-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_provider_remove_userpassword_application_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='private',
        ),
        migrations.AddField(
            model_name='provider',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('1', 'Social'), ('2', 'Media'), ('3', 'Game'), ('4', 'Bank'), ('5', 'Development'), ('6', 'Other')], default='1', max_length=2),
        ),
    ]
