# Generated by Django 4.1.5 on 2024-01-23 05:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userpassword_delete_alter_provider_provider_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='icon',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
