# Generated by Django 4.1.5 on 2024-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_provider_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='application_type',
        ),
    ]
